export const socialMediaIcons = [
  {
    name: 'GitHub',
    title: 'GitHub: stone-zeng',
    href: 'https://github.com/stone-zeng',
    external: true,
    color: ['#222222', '#dee2e6'],
    icon: 'github',
  },
  {
    name: 'Twitter',
    title: 'Twitter: xiangdong_zeng',
    href: 'https://twitter.com/xiangdong_zeng',
    external: true,
    color: '#1da1f2',
    icon: 'twitter',
  },
  {
    name: 'Telegram',
    title: 'Telegram: xdzeng96',
    href: 'https://t.me/xdzeng96',
    external: true,
    color: '#0088cc',
    icon: 'telegram',
  },
  {
    name: 'E-mail',
    title: 'E-mail: xdzeng96@gmail.com',
    href: 'mailto:xdzeng96@gmail.com',
    external: false,
    color: '#fbbf24',
    icon: 'email',
  },
  {
    name: 'RSS',
    title: 'RSS',
    href: '/feed.xml',
    external: false,
    color: '#f26522',
    icon: 'rss',
  },
];
